apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: open-cluster-management:work-manger:addon-manager
  namespace: hub1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: open-cluster-management:work-manger:addon-manager
subjects:
  - kind: ServiceAccount
    name: default
    namespace: hub1
